### ISSUE TITLE
Confusing Readme Text

### ISSUE THREAD

**Issue by daniel-frenkel** [espressif/esp-rainmaker-admin-cli#1]
In the README.md section on Flashing:

https://github.com/espressif/esp-rainmaker-admin-cli#flashing

This line is confusing because the use of back slashes makes it difficult to understand:

python esptool.py --port \<port\> write_flash <fctry_address> \<outdir\>/bin/\<filename\>.bin`

**Comment by shahpiyushv** [comment]
@daniel-frenkel , that is indeed confusing and not required since the line is already formatted using the backticks. We will fix this.
